import {revalidatePath} from 'next/cache'
import {requireAdmin} from '../../../lib/auth'
const BUCKET='parish-events'
const clean=v=>String(v||'').trim()||null
const safe=n=>String(n||'imagem').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').toLowerCase()
async function upload(s,file){if(!file?.size)return null;if(!String(file.type||'').startsWith('image/'))throw new Error('Envie uma imagem válida.');if(file.size>8*1024*1024)throw new Error('A imagem deve ter no máximo 8 MB.');const path=`${new Date().getFullYear()}/${Date.now()}-${safe(file.name)}`;const {error}=await s.storage.from(BUCKET).upload(path,Buffer.from(await file.arrayBuffer()),{contentType:file.type});if(error)throw error;return s.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}
async function save(fd){'use server';const {supabase:s}=await requireAdmin();const id=clean(fd.get('id'));const img=await upload(s,fd.get('image_file'))||clean(fd.get('image_existing'))||clean(fd.get('image_url'));const payload={title:clean(fd.get('title')),category:clean(fd.get('category')),summary:clean(fd.get('summary')),description:clean(fd.get('description')),location:clean(fd.get('location')),starts_at:new Date(fd.get('starts_at')).toISOString(),ends_at:clean(fd.get('ends_at'))?new Date(fd.get('ends_at')).toISOString():null,image_url:img,responsible:clean(fd.get('responsible')),featured:fd.get('featured')==='on',active:true,updated_at:new Date().toISOString()};if(id){const {error}=await s.from('parish_events').update(payload).eq('id',id);if(error)throw error}else{const {error}=await s.from('parish_events').insert(payload);if(error)throw error}revalidatePath('/admin/agenda');revalidatePath('/agenda');revalidatePath('/')}
async function act(fd){'use server';const {supabase:s}=await requireAdmin();const id=fd.get('id');if(fd.get('op')==='delete')await s.from('parish_events').delete().eq('id',id);else await s.from('parish_events').update({active:fd.get('active')!=='true'}).eq('id',id);revalidatePath('/admin/agenda');revalidatePath('/agenda');revalidatePath('/')}
const local=v=>v?new Date(v).toLocaleString('pt-BR'):'—';const inputDate=v=>v?new Date(new Date(v).getTime()-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16):''
export default async function Page(){const {supabase:s}=await requireAdmin();const {data,error}=await s.from('parish_events').select('*').order('starts_at',{ascending:false});const rows=data||[];return <><div className="adminTitle"><small>VIDA PAROQUIAL</small><h1>Agenda Paroquial</h1><p>Cadastre celebrações especiais, reuniões, retiros, formações e eventos das pastorais.</p></div>{error&&<div className="adminAlert">A Agenda ainda não está disponível. Execute o SQL da V6.15 no Supabase.</div>}<details className="adminCreate" open={!rows.length}><summary>+ Novo evento</summary><EventForm action={save}/></details><div className="adminCards eventAdminCards">{rows.map(x=><article key={x.id}>{x.image_url&&<img className="eventAdminImage" src={x.image_url} alt=""/>}<div className="rowBetween"><div><small>{x.category||'EVENTO'}</small><h3>{x.title}</h3></div><span className={x.active?'status on':'status'}>{x.active?'Publicado':'Inativo'}</span></div><p><b>{local(x.starts_at)}</b>{x.ends_at?` até ${local(x.ends_at)}`:''}<br/>{x.location||''}</p>{x.featured&&<small>★ Exibir entre os próximos eventos da página inicial</small>}<details><summary>Editar</summary><EventForm action={save} x={x}/></details><div className="actions"><form action={act}><input type="hidden" name="id" value={x.id}/><input type="hidden" name="active" value={String(x.active)}/><button>{x.active?'Desativar':'Ativar'}</button></form><form action={act}><input type="hidden" name="id" value={x.id}/><input type="hidden" name="op" value="delete"/><button className="danger">Excluir</button></form></div></article>)}</div></>}
function EventForm({action,x={}}){return <form action={action} className="adminForm"><input type="hidden" name="id" value={x.id||''}/><input type="hidden" name="image_existing" value={x.image_url||''}/><div className="formTwo"><label>Categoria<input name="category" defaultValue={x.category||''} placeholder="Ex.: SOLENIDADE, RETIRO, PASTORAL"/></label><label>Pastoral / responsável<input name="responsible" defaultValue={x.responsible||''} placeholder="Ex.: PASCOM"/></label></div><label>Título<input name="title" required defaultValue={x.title||''}/></label><label>Resumo<textarea name="summary" rows="2" defaultValue={x.summary||''}/></label><label>Descrição<textarea name="description" rows="5" defaultValue={x.description||''}/></label><div className="formTwo"><label>Início<input type="datetime-local" name="starts_at" required defaultValue={inputDate(x.starts_at)}/></label><label>Término (opcional)<input type="datetime-local" name="ends_at" defaultValue={inputDate(x.ends_at)}/></label></div><label>Local<input name="location" defaultValue={x.location||''} placeholder="Ex.: Igreja Matriz, Salão Paroquial..."/></label><div className="formTwo"><label>Imagem do evento<input type="file" name="image_file" accept="image/*"/><small className="adminHint">Máximo 8 MB.</small></label><label>Ou URL da imagem<input name="image_url" placeholder="https://..."/></label></div><label className="checkLine"><input type="checkbox" name="featured" defaultChecked={!!x.featured}/> Mostrar nos próximos eventos da página inicial</label><button>{x.id?'Salvar alterações':'Cadastrar evento'}</button></form>}
