import {revalidatePath} from 'next/cache'
import {requireAdmin} from '../../../lib/auth'
const BUCKET='parish-spirituality'
const clean=v=>String(v||'').trim()||null
const safe=n=>String(n||'imagem').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').toLowerCase()
async function upload(s,file){if(!file?.size)return null;if(!String(file.type||'').startsWith('image/'))throw new Error('Envie uma imagem válida.');if(file.size>8*1024*1024)throw new Error('A imagem deve ter no máximo 8 MB.');const path=`${new Date().getFullYear()}/${Date.now()}-${safe(file.name)}`;const {error}=await s.storage.from(BUCKET).upload(path,Buffer.from(await file.arrayBuffer()),{contentType:file.type});if(error)throw error;return s.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}
async function save(fd){'use server';const {supabase:s}=await requireAdmin();const id=clean(fd.get('id'));const image=await upload(s,fd.get('image_file'))||clean(fd.get('image_existing'))||clean(fd.get('image_url'));const payload={category:clean(fd.get('category')),title:clean(fd.get('title')),summary:clean(fd.get('summary')),content:clean(fd.get('content')),author:clean(fd.get('author')),image_url:image,audio_url:clean(fd.get('audio_url')),video_url:clean(fd.get('video_url')),featured:fd.get('featured')==='on',active:fd.get('active')==='on',published_at:clean(fd.get('published_at'))?new Date(fd.get('published_at')).toISOString():new Date().toISOString(),updated_at:new Date().toISOString()};const q=id?s.from('spiritual_content').update(payload).eq('id',id):s.from('spiritual_content').insert(payload);const {error}=await q;if(error)throw error;revalidatePath('/admin/formacao');revalidatePath('/formacao');revalidatePath('/')}
async function act(fd){'use server';const {supabase:s}=await requireAdmin();const id=fd.get('id');if(fd.get('op')==='delete')await s.from('spiritual_content').delete().eq('id',id);else await s.from('spiritual_content').update({active:fd.get('active')!=='true'}).eq('id',id);revalidatePath('/admin/formacao');revalidatePath('/formacao');revalidatePath('/')}
const inputDate=v=>v?new Date(new Date(v).getTime()-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16):''
export default async function Page(){const {supabase:s}=await requireAdmin();const {data,error}=await s.from('spiritual_content').select('*').order('published_at',{ascending:false});const rows=data||[];return <><div className="adminTitle"><small>EVANGELIZAÇÃO</small><h1>Formação e Espiritualidade</h1><p>Publique Palavra do Pároco, formações, reflexões, homilias e orações sem alterar o código do site.</p></div>{error&&<div className="adminAlert">O módulo ainda não está disponível. Execute primeiro o SQL da V6.16 no Supabase.</div>}<details className="adminCreate" open={!rows.length}><summary>+ Nova publicação</summary><ContentForm action={save}/></details><div className="adminCards spiritualAdminCards">{rows.map(x=><article key={x.id}>{x.image_url&&<img className="spiritualAdminImage" src={x.image_url} alt=""/>}<div className="rowBetween"><div><small>{x.category}</small><h3>{x.title}</h3></div><span className={x.active?'status on':'status'}>{x.active?'Publicado':'Rascunho'}</span></div><p>{x.summary}</p><small>{x.author||'Paróquia São José'} · {new Date(x.published_at).toLocaleDateString('pt-BR')}</small>{x.featured&&<p><small>★ Destaque na página inicial</small></p>}<details><summary>Editar</summary><ContentForm action={save} x={x}/></details><div className="actions"><form action={act}><input type="hidden" name="id" value={x.id}/><input type="hidden" name="active" value={String(x.active)}/><button>{x.active?'Mover para rascunho':'Publicar'}</button></form><form action={act}><input type="hidden" name="id" value={x.id}/><input type="hidden" name="op" value="delete"/><button className="danger">Excluir</button></form></div></article>)}</div></>}
function ContentForm({action,x={}}){return <form action={action} className="adminForm"><input type="hidden" name="id" value={x.id||''}/><input type="hidden" name="image_existing" value={x.image_url||''}/><div className="formTwo"><label>Categoria<select name="category" defaultValue={x.category||'Formação Católica'}><option>Palavra do Pároco</option><option>Formação Católica</option><option>Reflexão</option><option>Homilia</option><option>Oração</option><option>Espiritualidade</option></select></label><label>Autor<input name="author" defaultValue={x.author||''} placeholder="Ex.: Padre Vandilson"/></label></div><label>Título<input name="title" required defaultValue={x.title||''}/></label><label>Resumo<textarea name="summary" rows="3" defaultValue={x.summary||''} placeholder="Texto breve para os cards e para a página inicial."/></label><label>Conteúdo completo<textarea name="content" rows="12" required defaultValue={x.content||''}/></label><div className="formTwo"><label>Imagem de capa<input type="file" name="image_file" accept="image/*"/><small className="adminHint">JPG, PNG ou WebP. Máximo 8 MB.</small></label><label>Ou URL da imagem<input name="image_url" defaultValue="" placeholder="https://..."/></label></div><div className="formTwo"><label>Áudio (URL opcional)<input type="url" name="audio_url" defaultValue={x.audio_url||''} placeholder="https://...mp3"/></label><label>Vídeo (URL opcional)<input type="url" name="video_url" defaultValue={x.video_url||''} placeholder="YouTube ou outra página de vídeo"/></label></div><label>Data de publicação<input type="datetime-local" name="published_at" defaultValue={inputDate(x.published_at)||inputDate(new Date())}/></label><label className="checkLine"><input type="checkbox" name="featured" defaultChecked={!!x.featured}/> Destacar na página inicial</label><label className="checkLine"><input type="checkbox" name="active" defaultChecked={x.id?!!x.active:true}/> Publicar agora</label><button>{x.id?'Salvar alterações':'Criar publicação'}</button></form>}
