'use client'
import {useMemo,useState} from 'react'
const mysteries={
 Gozosos:[['A Anunciação do Anjo a Maria','Contemplemos o sim de Maria e peçamos um coração disponível à vontade de Deus.'],['A Visitação de Maria a Isabel','Peçamos a graça de levar Cristo com alegria ao encontro de quem precisa.'],['O Nascimento de Jesus','Contemplemos a humildade de Deus que vem morar entre nós.'],['A Apresentação do Menino Jesus','Ofereçamos nossa vida ao Senhor com confiança.'],['O Encontro de Jesus no Templo','Peçamos perseverança para buscar Jesus em todos os momentos.']],
 Luminosos:[['O Batismo de Jesus no Jordão','Renovemos a graça de nosso batismo e nossa identidade de filhos de Deus.'],['As Bodas de Caná','Confiemos a Maria nossas necessidades e façamos tudo o que Jesus nos disser.'],['O Anúncio do Reino de Deus','Peçamos conversão e coragem para viver o Evangelho.'],['A Transfiguração de Jesus','Contemplemos a glória de Cristo e aprendamos a escutá-lo.'],['A Instituição da Eucaristia','Agradeçamos o dom de Jesus que permanece conosco na Eucaristia.']],
 Dolorosos:[['A Agonia de Jesus no Horto','Unamos nossas angústias à entrega confiante de Jesus ao Pai.'],['A Flagelação de Jesus','Rezemos pelos que sofrem no corpo e na alma.'],['A Coroação de Espinhos','Peçamos humildade e fidelidade diante das humilhações.'],['Jesus carrega a Cruz','Ofereçamos nossas cruzes e ajudemos a carregar as dos irmãos.'],['A Crucifixão e Morte de Jesus','Contemplemos o amor que se entrega até o fim.']],
 Gloriosos:[['A Ressurreição de Jesus','Alegremo-nos na vitória da vida sobre a morte.'],['A Ascensão do Senhor','Elevemos o coração e vivamos com esperança.'],['A Vinda do Espírito Santo','Peçamos os dons do Espírito Santo para a Igreja e nossas famílias.'],['A Assunção de Maria','Contemplemos Maria elevada ao céu, sinal de esperança.'],['A Coroação de Maria','Confiemos à Rainha da Paz nossas famílias e nossa comunidade.']]
}
const p={
 sinal:'Em nome do Pai, e do Filho, e do Espírito Santo. Amém.',
 creio:'Creio em Deus Pai todo-poderoso, Criador do céu e da terra; e em Jesus Cristo, seu único Filho, nosso Senhor; que foi concebido pelo poder do Espírito Santo; nasceu da Virgem Maria; padeceu sob Pôncio Pilatos, foi crucificado, morto e sepultado; desceu à mansão dos mortos; ressuscitou ao terceiro dia; subiu aos céus; está sentado à direita de Deus Pai todo-poderoso, donde há de vir a julgar os vivos e os mortos. Creio no Espírito Santo; na Santa Igreja Católica; na comunhão dos santos; na remissão dos pecados; na ressurreição da carne; na vida eterna. Amém.',
 pai:'Pai nosso que estais nos céus, santificado seja o vosso nome; venha a nós o vosso reino; seja feita a vossa vontade, assim na terra como no céu. O pão nosso de cada dia nos dai hoje; perdoai-nos as nossas ofensas, assim como nós perdoamos a quem nos tem ofendido; e não nos deixeis cair em tentação, mas livrai-nos do mal. Amém.',
 ave:'Ave Maria, cheia de graça, o Senhor é convosco; bendita sois vós entre as mulheres e bendito é o fruto do vosso ventre, Jesus. Santa Maria, Mãe de Deus, rogai por nós pecadores, agora e na hora de nossa morte. Amém.',
 gloria:'Glória ao Pai, ao Filho e ao Espírito Santo. Como era no princípio, agora e sempre. Amém.',
 fatima:'Ó meu Jesus, perdoai-nos, livrai-nos do fogo do inferno, levai as almas todas para o céu e socorrei principalmente as que mais precisarem.',
 salve:'Salve, Rainha, Mãe de misericórdia, vida, doçura e esperança nossa, salve! A vós bradamos, os degredados filhos de Eva. A vós suspiramos, gemendo e chorando neste vale de lágrimas. Eia, pois, advogada nossa, esses vossos olhos misericordiosos a nós volvei; e depois deste desterro, mostrai-nos Jesus, bendito fruto do vosso ventre. Ó clemente, ó piedosa, ó doce sempre Virgem Maria. Rogai por nós, Santa Mãe de Deus, para que sejamos dignos das promessas de Cristo. Amém.'
}
function todayMystery(){const d=new Date().getDay();if(d===1||d===6)return'Gozosos';if(d===2||d===5)return'Dolorosos';if(d===4)return'Luminosos';return'Gloriosos'}
function buildSteps(type){const out=[{title:'Sinal da Cruz',text:p.sinal},{title:'Creio',text:p.creio},{title:'Pai-Nosso',text:p.pai},{title:'1ª Ave-Maria — pela fé',text:p.ave},{title:'2ª Ave-Maria — pela esperança',text:p.ave},{title:'3ª Ave-Maria — pela caridade',text:p.ave},{title:'Glória ao Pai',text:p.gloria}];mysteries[type].forEach((m,di)=>{out.push({title:`${di+1}º Mistério — ${m[0]}`,text:m[1],mystery:di,kind:'announce'});out.push({title:'Pai-Nosso',text:p.pai,mystery:di,kind:'ourfather'});for(let i=1;i<=10;i++)out.push({title:`${i}ª Ave-Maria`,text:p.ave,mystery:di,bead:i,kind:'ave'});out.push({title:'Glória ao Pai',text:p.gloria,mystery:di,bead:10,kind:'glory'});out.push({title:'Ó meu Jesus',text:p.fatima,mystery:di,bead:10,kind:'fatima'})});out.push({title:'Salve Rainha',text:p.salve,kind:'final'});out.push({title:'Sinal da Cruz',text:p.sinal,kind:'final'});return out}
export default function RosaryPlayer(){const [type,setType]=useState(todayMystery());const [started,setStarted]=useState(false);const [idx,setIdx]=useState(0);const steps=useMemo(()=>buildSteps(type),[type]);const step=steps[idx];const progress=Math.round(((idx+1)/steps.length)*100);function reset(){setStarted(false);setIdx(0);if(typeof window!=='undefined')window.speechSynthesis?.cancel()}function speak(){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${step.title}. ${step.text}`);u.lang='pt-BR';u.rate=.9;window.speechSynthesis.speak(u)}return <div className="rosaryApp"><div className="mysteryTabs">{Object.keys(mysteries).map(x=><button className={x===type?'active':''} key={x} onClick={()=>{setType(x);setStarted(false);setIdx(0)}}>{x}</button>)}</div>{!started?<div className="rosaryStart"><div className="rosarySymbol">✝</div><h2>Mistérios {type}</h2><p>Para hoje, sugerimos os Mistérios <b>{todayMystery()}</b>. O roteiro inclui as orações iniciais, os cinco mistérios, cada dezena e a Salve Rainha.</p><button className="goldBtn" onClick={()=>setStarted(true)}>INICIAR O TERÇO</button></div>:<div className="rosaryPrayer"><div className="progress"><span style={{width:`${progress}%`}}/></div><small>Passo {idx+1} de {steps.length}</small><h2>{step.title}</h2>{step.mystery!==undefined&&<p className="meditation"><b>{mysteries[type][step.mystery][0]}</b><br/>{mysteries[type][step.mystery][1]}</p>}{step.kind==='ave'&&<div className="beads">{Array.from({length:10},(_,i)=><span key={i} className={i<step.bead?'done':''}/>)}</div>}<div className="prayerText"><p>{step.text}</p></div><div className="rosaryActions"><button onClick={speak}>🔊 Ouvir</button>{idx>0&&<button className="ghost" onClick={()=>setIdx(idx-1)}>← Voltar</button>}{idx<steps.length-1?<button className="goldBtn" onClick={()=>setIdx(idx+1)}>Próxima oração →</button>:<button className="goldBtn" onClick={reset}>Concluir o Terço</button>}<button className="ghost" onClick={reset}>Recomeçar</button></div></div>}</div>}
